replicaCount: 1
image:
  repository: 3
  pullPolicy: IfNotPresent
  tag: 2024-05-04-1714827874-8950701481
imagePullSecrets: []
nameOverride: rustapp
fullnameOverride: rustapp
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ''
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 3500
ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts:
    - host: rustdemo.t4cdigital.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources: {}
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
